### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by mian24** [ecjtuseclab/AILoginBlasting#1]
作者大佬们可以解决一下这个问题吗？

C:\Users\Downloads\验证码爆破\ClientBlastingLocal>python Main.py
2020-08-04 11:43:43.061516: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-04 11:43:43.066721: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "Main.py", line 252, in <module>
    main = Main()
  File "Main.py", line 26, in __init__
    self.CR = CRMain()
  File "C:\Users\Downloads\验证码爆破\ClientBlastingLocal\CaptchaRecognition\CRMain.py", line 27, in __init__
    self.model = train.Model(self.MAX_CAPTCHA, self.Is_alphabet, 35, 120, model_path=self.model_dir, train_image_path=self.train_image_path, valid_image_path=self.valid_image_path)
  File "C:\Users\Downloads\验证码爆破\ClientBlastingLocal\CaptchaRecognition\train.py", line 26, in __init__
    self.X = tf.placeholder(tf.float32, [None, self.IMAGE_HEIGHT * self.IMAGE_WIDTH])
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by m0w3n** [comment]
这个是tf版本引起的问题。参考下面的解决办法
https://blog.csdn.net/flowingfog/article/details/93597697
